[versions]
okhttp = "5.1.0"
slf4j =  "2.0.17"
kotlinx = "1.9.0"

[libraries]
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j"}
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx"}
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx"}